
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores.sinctactico_archivos;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int STRING_LITERAL = 24;
  public static final int FUNCTION = 2;
  public static final int CASO = 12;
  public static final int MULT = 37;
  public static final int CONST = 8;
  public static final int SI = 9;
  public static final int FUNCION = 3;
  public static final int LPAREN = 43;
  public static final int GREATER = 28;
  public static final int MINUS = 36;
  public static final int LESS = 29;
  public static final int RPAREN = 44;
  public static final int BOOLEAN_LITERAL = 20;
  public static final int SEMICOLON = 45;
  public static final int NOT = 34;
  public static final int AND = 32;
  public static final int SINO = 10;
  public static final int OR = 33;
  public static final int COMMA = 46;
  public static final int MIENTRAS = 15;
  public static final int ESCRIBIR = 19;
  public static final int DIV = 38;
  public static final int PLUS = 35;
  public static final int ASSIGN = 40;
  public static final int NULL_LITERAL = 21;
  public static final int DOT = 47;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int error = 1;
  public static final int MOD = 39;
  public static final int EQ = 26;
  public static final int ROMPER = 14;
  public static final int COLON = 48;
  public static final int LBRACE = 41;
  public static final int NOT_EQ = 27;
  public static final int LESS_EQ = 31;
  public static final int LET = 6;
  public static final int RBRACE = 42;
  public static final int LEER = 18;
  public static final int SEGUN = 11;
  public static final int HACER = 16;
  public static final int PARA = 17;
  public static final int RETORNAR = 5;
  public static final int FLOAT_LITERAL = 23;
  public static final int DEFECTO = 13;
  public static final int VAR = 7;
  public static final int INTEGER_LITERAL = 22;
  public static final int IDENTIFIER = 25;
  public static final int GREATER_EQ = 30;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "FUNCTION",
  "FUNCION",
  "RETURN",
  "RETORNAR",
  "LET",
  "VAR",
  "CONST",
  "SI",
  "SINO",
  "SEGUN",
  "CASO",
  "DEFECTO",
  "ROMPER",
  "MIENTRAS",
  "HACER",
  "PARA",
  "LEER",
  "ESCRIBIR",
  "BOOLEAN_LITERAL",
  "NULL_LITERAL",
  "INTEGER_LITERAL",
  "FLOAT_LITERAL",
  "STRING_LITERAL",
  "IDENTIFIER",
  "EQ",
  "NOT_EQ",
  "GREATER",
  "LESS",
  "GREATER_EQ",
  "LESS_EQ",
  "AND",
  "OR",
  "NOT",
  "PLUS",
  "MINUS",
  "MULT",
  "DIV",
  "MOD",
  "ASSIGN",
  "LBRACE",
  "RBRACE",
  "LPAREN",
  "RPAREN",
  "SEMICOLON",
  "COMMA",
  "DOT",
  "COLON"
  };
}

